apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-api-pvc
  namespace: kt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi