apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-api-pvc
  namespace: kt
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: service-api-volume